Update syncthing-conflicts.10m.py
Python3 hardcoded to avoid Travis CI error:

$ brew outdated python || brew upgrade python
$ brew outdated python@2 || brew upgrade python@2
Error: No available formula with the name "python@2"
Error: No available formula with the name "python@2"
The command "brew outdated python@2 || brew upgrade python@2" failed and exited with 1 during .